# Generated by Django 3.0.3 on 2020-02-11 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('resumo', models.CharField(max_length=400)),
                ('categoria', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y')),
                ('publicada', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autor.Autor')),
            ],
        ),
    ]
